- id: doi:10.1109/BIBM49941.2020.9313428
  image: https://d3smihljt9218e.cloudfront.net/event/59/logo/small-05e6fdd38ac17bfddebc838a4069a756.png
  extra-links:
    - type: manubot
      link: https://greenelab.github.io/knowledge-graph-review/
  tags:
    - histopathology image
    - image transformation
    - image segmentation
    - unlabeled data

- id: doi:10.1109/CBMS49503.2020.00069
  image: http://www.cbms2020.org/images/logo-cbms2020-v1.png
  tags:
    - cell tracking

- id: doi:https://doi.org/10.1101/491035
  image: https://www.allencell.org/uploads/8/1/9/9/81996008/published/overview-2020-12.png?1607460428
  extra-links:
    - type: website
      link: https://www.allencell.org/segmenter.html
    - type: source
      link: https://github.com/AllenCell/aics-ml-segmentation
      text: ML segmentation source
    - type: source
      link: https://github.com/AllenCell/aics-segmentation
      text: classic segmentation source
  tags:
    - image segmentation
    - light microscopy image
    - 3D

- id: doi:10.1109/ISBI.2019.8759430
  image: https://biomedicalimaging.org/2019/wp-content/uploads/sites/43/2018/03/ISBI_2019_banner_web-960.jpg
  tags:
    - image segmentation
    - 3D

- id: doi:https://doi.org/10.1609/aaai.v33i01.33015901
  image: https://aaai.org/Conferences/AAAI-19/wp-content/uploads/2017/09/AAAI-19-Hawaii-Beach-Shade.png
  tags:
    - image segmentation
    - efficient annotation

- id: doi:10.1109/ISBI.2018.8363724
  image: https://aaai.org/Conferences/AAAI-19/wp-content/uploads/2017/09/AAAI-19-Hawaii-Beach-Shade.png
  tags:
    - image registration
    
- id: doi:https://doi.org/10.1007/978-3-319-66185-8_3
  image: https://aaai.org/Conferences/AAAI-19/wp-content/uploads/2017/09/AAAI-19-Hawaii-Beach-Shade.png
  tags:
    - image segmentation

    